### PR TITLE
Added a new test case for product image with correct string

### PR DESCRIPTION
**Pull request by dkakandki**

### CODE REVIEW

**Review by korsbacken — APPROVED** [review]
Approved.

**Comment by korsbacken** [comment]
I saw that you have added some TestNG dependencies in the POM-file in some earlier commit, I don't know if that is necessary 🤔 Anyway, it does not make any difference 😃 Go ahead with merge 👍

**Comment by dkakandki** [comment]
Do you mean in the same repo bcz i just have made changes to  tests file. we can talk about it in the next meeting.

**Comment by korsbacken** [comment]
I think I got a little bit confused. I was looking at your commits and then I went to your remote branch and checked the POM-file and saw the TestNG dependencies. I thought that was a part of the commit, but it wasn't I realized now. All is good 👍

**Pull request merged**
